import { mkdirSync, writeFileSync, rmSync, readdirSync } from "node:fs";

/**
 * Writes every template to /email-previews as a standalone .html and a
 * .txt, so they can be opened directly or pasted into Litmus or Email on
 * Acid later.
 *
 * It pulls from the SAME running dev server the preview route uses
 * (/dev/emails/export), so the files and the page cannot drift.
 *
 *   npm run emails:export        (dev server must be running)
 */

const BASE = process.env.BASE ?? "http://localhost:3000";
const OUT = "email-previews";

const res = await fetch(`${BASE}/dev/emails/export`);
if (!res.ok) {
  console.error(
    `Could not reach ${BASE}/dev/emails/export (${res.status}). Is the dev server running?`
  );
  process.exit(1);
}
const items = await res.json();

// Clear only what THIS script generates. A blanket rmSync took
// CHECKLIST.md with it, which is hand-written and lives here on purpose.
mkdirSync(OUT, { recursive: true });
for (const f of readdirSync(OUT)) {
  if (/\.(html|txt)$/.test(f) || f === "README.md") rmSync(`${OUT}/${f}`);
}

const index = [];
for (const t of items) {
  writeFileSync(`${OUT}/${t.id}.html`, t.html, "utf8");
  writeFileSync(`${OUT}/${t.id}.txt`, t.text, "utf8");
  index.push(
    `- ${t.id}.html / .txt — ${t.name} (to ${t.audience === "visitor" ? "the visitor" : "sales@"}) — subject: ${t.subject}`
  );
  console.log(`  ${t.id}.html  ${t.text.length} chars of text`);
}

writeFileSync(
  `${OUT}/README.md`,
  `# Email previews

Generated by \`npm run emails:export\` from the same renderer the app
sends with. Do not edit these by hand: regenerate instead.

Every template has a \`.txt\` beside it, which is the real text/plain part
that ships with the send. Transactional mail without one is filtered
aggressively.

The visitor templates reference the logo by absolute URL. Opened from
disk before the site is deployed, that image will not load — which is
also a useful preview of what a recipient with images blocked sees.

${index.join("\n")}
`,
  "utf8"
);

console.log(`\n${items.length} templates written to ${OUT}/`);
